### ISSUE TITLE
Mount/Unmount count to avoid unstyling

### ISSUE THREAD

**Issue by cusspvz** [bloodyowl/react-styled#4]
I was thinking on writing a `decorator` which would enable or disable `style/usable` webpack modules on mount and unmount... Guess what, you already had! 🎯 THANKS! :D

Just one thing, this could possibly have an issue. I was thinking on having my `decorator` with a sort of a counter, so it would only unload styles when there aren't components mounted.

One brief example could be a button component, you could have one on a page header, if you enter a page where you have another, it will load styles again, but if you navigate outside of that page, the button o the header would be without styling. And I don't see where you're predicting that behavior on the code yet.

**Comment by bloodyowl** [comment]
the counter is on webpack plugin's side (https://github.com/bloodyowl/react-styled/blob/master/src/index.js#L31, decrement on each unmount) this should work directly (or do you have a repro to show unusual behaviour with this?)

**Comment by cusspvz** [comment]
Oh!! NICEEE!

I've tested it and it worked, also [checked your statement](https://github.com/webpack/style-loader/blob/master/useable.js#L17), didn't know bout it, sorry.

> do you have a repro to show unusual behaviour with this?

No, please ignore this issue. :)
