### ISSUE TITLE
Change from `componentWillMount` to `componentDidMount`

### ISSUE THREAD

**Issue by cusspvz** [bloodyowl/react-styled#6]
So we can make this compatible with Universal JS, we must ensure the styles code aren't run on the server side. As server executes `componentWillMount`, the better would be to change the useability check to the `componentDidMount` hook on the Component's life cycle.

**Comment by bloodyowl** [comment]
if we use `componentDidMount`, there might be a flash of unstyled content (w/ webpack you can use `ExtractTextPlugin` on the server to extract CSS contents and inject it somewhere else)

**Comment by cusspvz** [comment]
Could this be an option?

**Comment by bloodyowl** [comment]
well, if you render your components on the server, I guess you want the right styles to be in the page on initial load, right?

`componentDidMount` isn't called with `ReactDOMServer`, which means the server wouldn't have any idea which CSS to put in the page initially

**Comment by cusspvz** [comment]
But are you shipping the CSS from the server?

**Comment by cusspvz** [comment]
On the project I'm using this I have webpack handling both server and browser builds, on the server build I've attached the `null-loader` instead, because the server won't ever build a DOM, neither the `style-loader/useable` would work on the server, or am I wrong? 😕

**Comment by cusspvz** [comment]
PS: Even if you are loading CSS on the server for you to know which classes you need to render, you won't need to call `use()`, I'm really interested to know how you've builded or shipped CSS from within the server. On every scenarios I'm thinking on, I'm supposing it would give errors, memory leaks or bottlenecks.
